
external_components:
  - source: github.com/FujiHeatPump/esphome-fujitsu/tree/master/src

esphome:
  includes:
    - FujitsuClimate.h
    - FujitsuClimate.cpp
    - FujiHeatPump.h
    - FujiHeatPump.cpp

climate:
  - platform: custom
    lambda: |-
      auto fujitsuClimate = new fujitsu::FujitsuClimate();
      App.register_component(fujitsuClimate);
      return {fujitsuClimate};

    climates:
      - name: "Master"
        id: master
